[package]
name = "RustJWT"
version = "0.1.0"
authors = ["Johan Gardell <johan@gardell.me>"]

[dependencies]
base64 = "~0.4.0"
rust-crypto = "^0.2"
serde = "0.9.7"
serde_derive = "0.9.7"
serde_json = "0.9.7"